# Eliminación Gaussiana

In [3]:
import numpy as np

Versión sencilla

In [9]:
def eliminacion_gaussiana(A,resultados_parciales=False):
    if resultados_parciales: print("Inicial:\n", A)
    n = A.shape[0]
    for k in range(n-1):
        for i in range(k+1,n):
            ratio = A[i,k]/A[k,k]
            for j in range(k,n+1):
                A[i,j] = A[i,j]-ratio*A[k,j]
            if resultados_parciales: print(A)
    if resultados_parciales: print("Forward elimination:\n",A)
    variables = A[:,n]
    for k in reversed(range(n)):
        for j in range(k+1,n):
            variables[k] = variables[k] - A[k,j]*variables[j] 
        variables[k] = variables[k]/A[k,k]
    print("Valor de las variables:\n",variables)
    return variables
    

Versión vectorizada

In [4]:
def eliminacion_gaussiana(A,resultados_parciales=False):
    if resultados_parciales: print("Inicial:\n", A)
    n = A.shape[0]
    for k in range(n-1):
        for i in range(k+1,n):
            ratio = A[i,k]/A[k,k]
            A[i] = A[i]-ratio*A[k]
            if resultados_parciales: print(A)
    if resultados_parciales: print("Forward elimination:\n",A)
    variables = A[:,n]
    for k in reversed(range(n)):
        for j in range(k+1,n):
            variables[k] = variables[k] - A[k,j]*variables[j] 
        variables[k] = variables[k]/A[k,k]
    print("Valor de las variables:\n",variables)
    return variables

Forward elimination:

In [11]:
A = np.array([[3,1,1,5],[4,4,6,6],[4,2,3,7]],dtype=float)
print("Inicial:\n", A)

n = A.shape[0]

for k in range(n-1):
    for i in range(k+1,n):
        ratio = A[i,k]/A[k,k]
        print(ratio)
        for j in range(k,n+1):
            A[i,j] = A[i,j]-ratio*A[k,j]
        print(A)

print("Final:\n",A)


Inicial:
 [[3. 1. 1. 5.]
 [4. 4. 6. 6.]
 [4. 2. 3. 7.]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 4.          2.          3.          7.        ]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
0.25
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]
Final:
 [[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]


Backwards substitution

In [12]:
variables = A[:,n]

for k in reversed(range(n)):
    for j in range(k+1,n):
        variables[k] = variables[k] - A[k,j]*variables[j] 
    variables[k] = variables[k]/A[k,k]

print("Valor de las variables:\n",variables)

Valor de las variables:
 [ 2. -2.  1.]


## Más ejemplos

In [5]:
A = np.array([[3,2,1,1],[5,3,4,2],[1,1,-1,1]],dtype=float)

eliminacion_gaussiana(A=A,resultados_parciales=True)

Inicial:
 [[ 3.  2.  1.  1.]
 [ 5.  3.  4.  2.]
 [ 1.  1. -1.  1.]]
[[ 3.          2.          1.          1.        ]
 [ 0.         -0.33333333  2.33333333  0.33333333]
 [ 1.          1.         -1.          1.        ]]
[[ 3.          2.          1.          1.        ]
 [ 0.         -0.33333333  2.33333333  0.33333333]
 [ 0.          0.33333333 -1.33333333  0.66666667]]
[[ 3.          2.          1.          1.        ]
 [ 0.         -0.33333333  2.33333333  0.33333333]
 [ 0.          0.          1.          1.        ]]
Forward elimination:
 [[ 3.          2.          1.          1.        ]
 [ 0.         -0.33333333  2.33333333  0.33333333]
 [ 0.          0.          1.          1.        ]]
Valor de las variables:
 [-4.  6.  1.]


array([-4.,  6.,  1.])

In [1]:
import linear_systems as ls

A,b,sol = ls.find_example(dim=3)

Matriz A:
 [[ 0 -3  3]
 [-4 -1  6]
 [ 8 -1  7]]
Lado derecho b:
 [[-6]
 [-7]
 [-8]]
Solución:
 [ 0.  1. -1.]


In [2]:
# A = np.array([[2,1,0,2,5],[5,3,4,2],[1,1,-1,1]],dtype=float)
import numpy as np
from linear_systems import eliminacion_gaussiana


A = np.array([[-3,1,-3],[-5,1,-1],[2,5,-6]],dtype=float)
b = np.array([2,-2,-8])

eliminacion_gaussiana(A=A,b=b,resultados_parciales=True)

Inicial:
 [[-3.  1. -3.  2.]
 [-5.  1. -1. -2.]
 [ 2.  5. -6. -8.]]
[[-3.          1.         -3.          2.        ]
 [ 0.         -0.66666667  4.         -5.33333333]
 [ 2.          5.         -6.         -8.        ]]
[[-3.          1.         -3.          2.        ]
 [ 0.         -0.66666667  4.         -5.33333333]
 [ 0.          5.66666667 -8.         -6.66666667]]
[[ -3.           1.          -3.           2.        ]
 [  0.          -0.66666667   4.          -5.33333333]
 [  0.           0.          26.         -52.        ]]
Forward elimination:
 [[ -3.           1.          -3.           2.        ]
 [  0.          -0.66666667   4.          -5.33333333]
 [  0.           0.          26.         -52.        ]]
Valor de las variables:
 [ 5.92118946e-16 -4.00000000e+00 -2.00000000e+00]


array([ 5.92118946e-16, -4.00000000e+00, -2.00000000e+00])

In [3]:
import numpy as np
from linear_systems import eliminacion_gaussiana


A = np.array([[-5,1,-1],[0,5.4,-6.4],[0,0,-1.92]],dtype=float)
b = np.array([-2,-8.8,3.851])

eliminacion_gaussiana(A=A,b=b,resultados_parciales=True)

Inicial:
 [[-5.     1.    -1.    -2.   ]
 [ 0.     5.4   -6.4   -8.8  ]
 [ 0.     0.    -1.92   3.851]]
[[-5.     1.    -1.    -2.   ]
 [ 0.     5.4   -6.4   -8.8  ]
 [ 0.     0.    -1.92   3.851]]
[[-5.     1.    -1.    -2.   ]
 [ 0.     5.4   -6.4   -8.8  ]
 [ 0.     0.    -1.92   3.851]]
[[-5.     1.    -1.    -2.   ]
 [ 0.     5.4   -6.4   -8.8  ]
 [ 0.     0.    -1.92   3.851]]
Forward elimination:
 [[-5.     1.    -1.    -2.   ]
 [ 0.     5.4   -6.4   -8.8  ]
 [ 0.     0.    -1.92   3.851]]
Valor de las variables:
 [-2.12191358e-04 -4.00679012e+00 -2.00572917e+00]


array([-2.12191358e-04, -4.00679012e+00, -2.00572917e+00])

# Método Gauss-Jordan

In [5]:
A = np.array([[3,1,1,5],[4,4,6,6],[4,2,3,7]],dtype=float)
print("Inicial:\n", A)

n = A.shape[0]

for k in range(n):
    for i in range(n):
        if i!=k:
            ratio = A[i,k]/A[k,k]
            print(ratio)
            for j in range(k,n+1):
                A[i,j] = A[i,j]-ratio*A[k,j]
            print(A)

print("Final:\n",A)

Inicial:
 [[3. 1. 1. 5.]
 [4. 4. 6. 6.]
 [4. 2. 3. 7.]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 4.          2.          3.          7.        ]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
0.37499999999999994
[[ 3.          0.         -0.75        5.25      ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
0.25
[[ 3.          0.         -0.75        5.25      ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]
-1.4999999999999996
[[ 3.          0.          0.          6.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]
9.333333333333334
[[ 3.          0.          0.          6.        ]
 [ 0.          2.66666