# Eliminación Gaussiana

In [1]:
import numpy as np

Forward elimination:

In [2]:
A = np.array([[3,1,1,5],[4,4,6,6],[4,2,3,7]],dtype=float)
print("Inicial:\n", A)

n = A.shape[0]

for k in range(n-1):
    for i in range(k+1,n):
        ratio = A[i,k]/A[k,k]
        print(ratio)
        for j in range(k,n+1):
            A[i,j] = A[i,j]-ratio*A[k,j]
        print(A)

print("Final:\n",A)


Inicial:
 [[3. 1. 1. 5.]
 [4. 4. 6. 6.]
 [4. 2. 3. 7.]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 4.          2.          3.          7.        ]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
0.25
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]
Final:
 [[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]


Backwards substitution

In [3]:
variables = A[:,n]

for k in reversed(range(n)):
    for j in range(k+1,n):
        variables[k] = variables[k] - A[k,j]*variables[j] 
    variables[k] = variables[k]/A[k,k]

print("Valor de las variables:\n",variables)

2
1
0
Valor de las variables:
 [ 2. -2.  1.]


Método Gauss-Jordan

In [5]:
A = np.array([[3,1,1,5],[4,4,6,6],[4,2,3,7]],dtype=float)
print("Inicial:\n", A)

n = A.shape[0]

for k in range(n):
    for i in range(n):
        if i!=k:
            ratio = A[i,k]/A[k,k]
            print(ratio)
            for j in range(k,n+1):
                A[i,j] = A[i,j]-ratio*A[k,j]
            print(A)

print("Final:\n",A)

Inicial:
 [[3. 1. 1. 5.]
 [4. 4. 6. 6.]
 [4. 2. 3. 7.]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 4.          2.          3.          7.        ]]
1.3333333333333333
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
0.37499999999999994
[[ 3.          0.         -0.75        5.25      ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
0.25
[[ 3.          0.         -0.75        5.25      ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]
-1.4999999999999996
[[ 3.          0.          0.          6.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]
9.333333333333334
[[ 3.          0.          0.          6.        ]
 [ 0.          2.66666