In [2]:
import numpy as np
from math import floor

In [27]:
dim = 5
n = 9
opciones = list(range(-n,n+1))

def check(x):
    s = False
    for x in X:
        if x-floor(x)==0:
            s = True
        else:
            s = False
            break
    return s

for k in range(10000):
    A = np.random.choice(opciones,size=(dim,dim),replace=True)
    b = np.random.choice(opciones,size=(dim,),replace=True)
    try:
        X = np.linalg.inv(A)@b
    except:
        pass
    if check(X):
        print(A)
        print(b.reshape((dim,1)))
        print(X)
        break


[[-3  1  1  1  4]
 [ 3 -8  3 -3  1]
 [ 2  8 -7  5 -5]
 [-3  4 -9  5  1]
 [ 1  7  1 -1 -7]]
[[-9]
 [-4]
 [-3]
 [-7]
 [-2]]
[ 6.48064403e+16  5.70296674e+16 -5.05490234e+16 -1.12763206e+17
  7.51754707e+16]


In [28]:
x = np.array([1,2,3,4,5])
A = np.array([[3,2,1,-3,5],[-1,0,4,-1,1],[1,4,2,3,0],[2,-2,1,-1,0],[3,1,1,7,-5]],dtype=float)
np.dot(A,x)

array([23., 12., 27., -3., 11.])