In [1]:
import numpy as np

# A = np.array([[3,2,1,-3,5,23],[-1,0,4,-1,1,12],[1,4,2,3,0,27],[2,-2,1,-1,0,-3],[3,1,1,7,-5,11]],dtype=float)
A = np.array([[3,1,1,5],[4,4,6,6],[4,2,3,7]],dtype=float)
print("Inicial:\n", A)

n = A.shape[0]

for k in range(n-1):
    for i in range(k+1,n):
        ratio = A[i,k]/A[k,k]
        for j in range(k,n+1):
            A[i,j] = A[i,j]-ratio*A[k,j]
        print(A)

print("\nFinal:\n",A)

Inicial:
 [[3. 1. 1. 5.]
 [4. 4. 6. 6.]
 [4. 2. 3. 7.]]
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 4.          2.          3.          7.        ]]
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.66666667  1.66666667  0.33333333]]
[[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]

Final:
 [[ 3.          1.          1.          5.        ]
 [ 0.          2.66666667  4.66666667 -0.66666667]
 [ 0.          0.          0.5         0.5       ]]


En MatLab se puede usar la notación `variables = A(:,end)`

In [2]:
variables = A[:,n]

for k in reversed(range(n)):
    for j in range(k+1,n):
        variables[k] = variables[k] - A[k,j]*variables[j] 
    variables[k] = variables[k]/A[k,k]

print("Valor de las variables:\n",variables)

Valor de las variables:
 [ 2. -2.  1.]
