In [1]:
import numpy as np
from math import floor

In [20]:
X = np.random.normal(loc=0,scale=1,size=(4,))
print(X)


[-0.14811617 -0.43367886 -1.77258141 -0.63739394]


True

In [21]:
dim = 4
N = 9   # cota del valor absoluto de los coeficientes
norma_max = 20
opciones = list(range(-N,N+1))


def are_integers(x):
    s = False
    for x in X:
        if x-floor(x)==0:
            s = True
        else:
            s = False
            break
    return s

def is_smaller_enough(X):
    return bool(np.prod(X<norma_max))


found = False
while not found:
    A = np.random.choice(opciones,size=(dim,dim),replace=True)
    b = np.random.choice(opciones,size=(dim,),replace=True)
    try:
        X = np.linalg.inv(A)@b
    except:
        pass
    if are_integers(X) and is_smaller_enough(X):
        print("Matriz A:\n",A)
        print("Lado derecho b:\n",b.reshape((dim,1)))
        print("Solución:\n",X)
        found = True


Matriz A:
 [[ 4  6  4  4]
 [ 5  8  0  8]
 [ 8 -2  0  6]
 [-4  6  6 -2]]
Lado derecho b:
 [[ 8]
 [-9]
 [ 6]
 [ 6]]
Solución:
 [ 3.  0.  2. -3.]
