In [1]:
import numpy as np

A = np.array([[3,2,1,-3,5,23],[-1,0,4,-1,1,12],[1,4,2,3,0,27],[2,-2,1,-1,0,-3],[3,1,1,7,-5,11]],dtype=float)
# A = np.array([[3,1,1,5],[4,4,6,6],[4,2,3,7]],dtype=float)
print("Inicial:\n", A)

n = A.shape[0]

for k in range(n-1):
    for i in range(k+1,n):
        ratio = A[i,k]/A[k,k]
        for j in range(k,n+1):
            A[i,j] = A[i,j]-ratio*A[k,j]
        print(A)

print("\nFinal:\n",A)

Inicial:
 [[ 3.  2.  1. -3.  5. 23.]
 [-1.  0.  4. -1.  1. 12.]
 [ 1.  4.  2.  3.  0. 27.]
 [ 2. -2.  1. -1.  0. -3.]
 [ 3.  1.  1.  7. -5. 11.]]
[[ 3.          2.          1.         -3.          5.         23.        ]
 [ 0.          0.66666667  4.33333333 -2.          2.66666667 19.66666667]
 [ 1.          4.          2.          3.          0.         27.        ]
 [ 2.         -2.          1.         -1.          0.         -3.        ]
 [ 3.          1.          1.          7.         -5.         11.        ]]
[[ 3.          2.          1.         -3.          5.         23.        ]
 [ 0.          0.66666667  4.33333333 -2.          2.66666667 19.66666667]
 [ 0.          3.33333333  1.66666667  4.         -1.66666667 19.33333333]
 [ 2.         -2.          1.         -1.          0.         -3.        ]
 [ 3.          1.          1.          7.         -5.         11.        ]]
[[  3.           2.           1.          -3.           5.
   23.        ]
 [  0.           0.66666667

In [2]:
variables = A[:,n]

for k in reversed(range(n)):
    for j in range(k+1,n):
        variables[k] = variables[k] - A[k,j]*variables[j] 
    variables[k] = variables[k]/A[k,k]

print("Valor de las variables:\n",variables)

Valor de las variables:
 [1. 2. 3. 4. 5.]
